// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACHVCEJw5rrxoVJHjZyRzxgYb-YPq38Cs',
    appId: '1:829371278833:android:c8add1f618557690055050',
    messagingSenderId: '829371278833',
    projectId: 'blood-bridge',
    databaseURL: 'https://blood-bridge-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bridge.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2z7M8rpV8p-x0MpvjSJeD5OluKTDtKgE',
    appId: '1:829371278833:ios:9c0233a53162fc5c055050',
    messagingSenderId: '829371278833',
    projectId: 'blood-bridge',
    databaseURL: 'https://blood-bridge-default-rtdb.firebaseio.com',
    storageBucket: 'blood-bridge.appspot.com',
    iosClientId: '829371278833-ipnq0633k3frm7vh3kl9ie6ggdk1j35r.apps.googleusercontent.com',
    iosBundleId: 'com.example.bloodBridge',
  );
}
