// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBonPtqMk7muObaWiyuPHV_LmB6ngcgfFY',
    appId: '1:295839847760:web:17a70ee45b0102ca200855',
    messagingSenderId: '295839847760',
    projectId: 'project-blood-bank-20389',
    authDomain: 'project-blood-bank-20389.firebaseapp.com',
    storageBucket: 'project-blood-bank-20389.appspot.com',
    measurementId: 'G-S380NZFQBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBV-Jqb4_OK_5pk4WHP4ZKfjfCeX_BModE',
    appId: '1:295839847760:android:2f5136e1da5d28df200855',
    messagingSenderId: '295839847760',
    projectId: 'project-blood-bank-20389',
    storageBucket: 'project-blood-bank-20389.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrFPu45ySorW9YndU62cK7aVObtP65-V8',
    appId: '1:295839847760:ios:8f20d8bd01445e15200855',
    messagingSenderId: '295839847760',
    projectId: 'project-blood-bank-20389',
    storageBucket: 'project-blood-bank-20389.appspot.com',
    iosClientId: '295839847760-hqqtha0auvba32rjlf79lselut1fb8ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrFPu45ySorW9YndU62cK7aVObtP65-V8',
    appId: '1:295839847760:ios:8f20d8bd01445e15200855',
    messagingSenderId: '295839847760',
    projectId: 'project-blood-bank-20389',
    storageBucket: 'project-blood-bank-20389.appspot.com',
    iosClientId: '295839847760-hqqtha0auvba32rjlf79lselut1fb8ij.apps.googleusercontent.com',
    iosBundleId: 'com.example.learnAuth',
  );
}
